const serompe = () => {
    return 3 + z;
}


try{
    serompe();
} catch(err){
    console.error('Hay una error en la aplicaci√≥n...')
}
